id: P004550
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W20202
  title: བོད་ས་གནས་ནི་ཀྲུང་གོའི་ཆ་ཤས་ཁ་བྲལ་ཐབས་མེད་པ་ཞིག་ཡིན།
  author: ''
  volumes:
    f5259aa783f4414e8905784cf0f76fa5:
      image_group_id: I1KG20843
      title: ''
      volume_number: 1
      total_pages: 468
